### ISSUE TITLE
can a colab notebook be created for this project?

### ISSUE THREAD

**Issue by GeorvityLabs** [abdallahdib/NextFace#1]
it would be great if you could setup a colab notebook with upload option.
Such that we could download the 3d render & texture and import it to tools like blender.

**Comment by abdallahdib** [comment]
Thanks for the suggestion, I will add a notebook for this.
please note the optimization produces a textured obj file compatible with blender-like softwares

**Comment by 2blackbar** [comment]
hugginface/replicate would be even better

**Comment by abdallahdib** [comment]
done a collab notebook is available here:

https://github.com/abdallahdib/NextFace/blob/main/demo.ipynb

**Comment by abdallahdib** [comment]
I am working on a huggingface version
