### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Michaelwhite34** [abdallahdib/NextFace#10]
2/3 => Optimizing shape, statistical albedos, expression, head pose and scene light...
  0%|                                                                                          | 0/401 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "optimizer.py", line 462, in <module>
    optimizer.run(inputDir,
  File "optimizer.py", line 419, in run
    self.runStep2()
  File "optimizer.py", line 233, in runStep2
    images = self.pipeline.render(cameraVerts, diffuseTextures, specularTextures)
  File "D:\NextFace\pipeline.py", line 124, in render
    scenes = self.renderer.buildScenes(cameraVerts, self.faces32, normals, self.uvMap, diffuseTextures,
  File "D:\NextFace\renderer.py", line 127, in buildScenes
    scene = pyredner.Scene(cam, materials=[mat], objects=[obj], envmap=pyredner.EnvironmentMap(envMap[i]))
  File "D:\anaconda3\envs\faceNext\lib\site-packages\pyredner\scene.py", line 56, in __init__
    shape = pyredner.Shape(vertices = obj.vertices,
  File "D:\anaconda3\envs\faceNext\lib\site-packages\pyredner\shape.py", line 371, in __init__
    assert(indices.is_contiguous())
AssertionError
Python 3.8 cuda 11.1

**Comment by abdallahdib** [comment]
NextFace is tested with pytorch 1.3.1 cuda 10.1 and python 3.6.5

i am planning to test on more recent pytorch/cuda version.

to fix ur issue, plz modify pipeline.py (line 25 with this new one): 
self.faces32 = self.morphableModel.faces.to(torch.int32).contiguous()

**Comment by Michaelwhite34** [comment]
Currently stuck at "saving to  xxxx ,hold on" Hope it will finish...

**Comment by Michaelwhite34** [comment]
It works,to produce to same render effect in blender,I need the estimated hdri which is not in the output.

**Comment by abdallahdib** [comment]
good news! 
i will add the light map to the output so that u can use with blender,

**Comment by Michaelwhite34** [comment]
> good news! i will add the light map to the output so that u can use with blender,

assert textureResolution == 256 or textureResolution == 512 #can handle only 256 or 512 texture res
AssertionError  Does it support higher res than 512?

**Comment by abdallahdib** [comment]
currently only 256 or 512, i will add HD (1024)

**Comment by Michaelwhite34** [comment]
> currently only 256 or 512, i will add HD (1024)

Or ,maybe 2048 ?

**Comment by abdallahdib** [comment]
okay

**Comment by Michaelwhite34** [comment]
> okay

I mean the detected bounding box of face should be 2048*2048...The actually photo is usually bigger than that (2 or 3 times).
The process is something like ,detected face ,resize of face box to 2048 then xxxx.The image is not resized before face detection,in that way it won't lose detail.

**Comment by Michaelwhite34** [comment]
If we have a GUI in the future,maybe we can manually adjust landmark ?

**Comment by Michaelwhite34** [comment]
The reason why we need 2048 is that sometimes we have high res image or we can use GAN to enhance face image.Also,2048 is pretty basic for CG usage.

**Comment by abdallahdib** [comment]
I have added uv maps for 1024 and 2048 resolution, 
u can download them from here: 
https://github.com/abdallahdib/NextFace/releases

plz put **uvParametrization.2048.pickle** and **uvParametrization.1024.pickle** inside **baselMorphableModel** and change the **textureResolution** in optimConfig.py to 1024 or 2048

also dont forget to pull

**Comment by abdallahdib** [comment]
also the GUI will allow to fix inaccurate landmarks, the best would be to use a better landmarks detector.

if you can halp in making the gui that edits the landmarks that would highly appreciated :) 

plz close the issue if u dont have other concerns

**Comment by Michaelwhite34** [comment]
> also the GUI will allow to fix inaccurate landmarks, the best would be to use a better landmarks detector.
> 
> if you can halp in making the gui that edits the landmarks that would highly appreciated :)
> 
> plz close the issue if u dont have other concerns

UDA Runtime Error: out of memory at C:\Users\Administrator\AppData\Local\Temp\2\pip-req-build-py6gcm7n\src\buffer.h:55
I guess it's OOM ? In cpu mode,the ETA is 10 hours for a single 2000*2000 image, kinda overwhelming.So,is there some way to use gpu without causing OOM ?

**Comment by abdallahdib** [comment]
yes, as expected, ray tracing is too much memory consuming. targeting 2048px for input images and textures resolution is too much. running on cpu is not an option for 10 hours :) 

mayeb u can sacrifice the resolution and downgraded to 1024 ? and not sure if this fits. did u try google colab they may offer large gpu memory?

**Comment by Michaelwhite34** [comment]
> yes, as expected, ray tracing is too much memory consuming. targeting 2048px for input images and textures resolution is too much. running on cpu is not an option for 10 hours :)
> 
> mayeb u can sacrifice the resolution and downgraded to 1024 ? and not sure if this fits. did u try google colab they may offer large gpu memory?

1024 takes 8 hours on cpu,there must be something wrong.

**Comment by abdallahdib** [comment]
what type of gpu/cpu do u have ? running on 1024/2048 is generally very costly, u may want to try upscaling the output texture of NextFace?

I dont think there is an issue with the scale, one u put the same camera parameters (focal and pose) u should retreive the same rendering as in the camera. I used to do this with opengl and it works. 
 
For the camera focal length and position (rotation and translation), they are saved in the **checkpoints/stage3_output.pickle** file 
this file is basically a dictionary file 
to get focal:
dict['vFocals']
dict['vRotation']
dict['vTranslation']
