### ISSUE TITLE
Google Colab error

### ISSUE THREAD

**Issue by xops37** [abdallahdib/NextFace#11]
Image of the error ![error](https://user-images.githubusercontent.com/69643439/164989517-9c5b5b1a-8434-44aa-9145-d4a4d94461fb.JPG)

Error occurs on the optimizer creation step, it says to "Download  "albedoModel2020_face12_albedoPart.h5",  and put it inside  /content/NextFace/baselMorphableModel/  and run again." But I've already done that as shown in the image.

**Comment by abdallahdib** [comment]
I just verified and everything is working on my side 
plz verify that the path are correct (see attached image)
![image](https://user-images.githubusercontent.com/2556636/164997585-9ed096c8-e9d7-481f-854a-5037aafd3058.png)

**Comment by xops37** [comment]
> I just verified and everything is working on my side plz verify that the path are correct (see attached image) ![image](https://user-images.githubusercontent.com/2556636/164997585-9ed096c8-e9d7-481f-854a-5037aafd3058.png)

Thanks for the info, I'll give it another try tomorrow

**Comment by ramnnv** [comment]
Im getting the same error on the last step "now we can run the optimization"...

i already check my paths and are ok, as default.

The error ocurrs on the second step:
2/3 => Optimizing shape, statistical albedos, expression, head pose and scene light...
  0%|          | 0/401 [00:00<?, ?it/s]

**Comment by abdallahdib** [comment]
did u try to restart colab runtime? the colab notebook is working fine on my side...

**Comment by MaayanBogin** [comment]
> Image of the error ![error](https://user-images.githubusercontent.com/69643439/164989517-9c5b5b1a-8434-44aa-9145-d4a4d94461fb.JPG)
> 
> Error occurs on the optimizer creation step, it says to "Download "albedoModel2020_face12_albedoPart.h5", and put it inside /content/NextFace/baselMorphableModel/ and run again." But I've already done that as shown in the image.

Yo! Had the same issue, Just change the name of the file "model2017-1_bfm_nomouth.h5" to "model2017-1_face12_nomouth.h5" and if you're still having problems, write 
print(os.path.exists("/content/NextFace/yourdir)) and try to get it to be true, change the names or play with the config.path or smth, Hope this helped
Best regards! really cool repo!

**Comment by abdallahdib** [comment]
@MaayanBogin is right, ur file name is not named correctly 
model2017-1_face12_nomouth.h5 is the one that next face needs, ur file is called differently i dont know why. did u download it from the correct link ? 

I will close the issue, u can reopen if needed
