### ISSUE TITLE
Cannot run demo Colab notebook due to missing normals.pickle file

### ISSUE THREAD

**Issue by JohnnyRacer** [abdallahdib/NextFace#13]
Hi, I've downloaded all the files for the BFM 2017 model as well as the albedos .h5 file. When I try loading the model it gives me an error message that I am missing 'normals.pickle'. Where can I find this file? There seems to be no mention of it anywhere in the repo. Any help is much appreciated!

**Comment by abdallahdib** [comment]
did u properly clone the repository ? the normals.pickle is on the repository here: 

https://github.com/abdallahdib/NextFace/tree/main/baselMorphableModel

plz ensure that the morphableModel directory contains these files (after a successful clone): 
![image](https://user-images.githubusercontent.com/2556636/165240846-125ba3ea-6e26-40be-803f-3ba508263c26.png)

**Comment by JohnnyRacer** [comment]
I had cloned the git repo correctly but I was loading the models directly from my Google Drive directory, which lacked the `normals.pickle` file. I didn't notice it was clone already in the original git directory. I think it could be useful to add a note somewhere in the exeception on the missing files to mention this or pull the file automatically from Github if its missing, since right now it doesn't mention . Thanks for the help anyways :)
