### ISSUE TITLE
How to get vertex position error and normal error

### ISSUE THREAD

**Issue by AndrewDQ** [abdallahdib/NextFace#17]
Hi, I want to know how to get vertex position error and normal error in your paper. Thank u.

**Comment by abdallahdib** [comment]
u will have to use dataset with groud truth mesh. such as AFLW OR 3DFA (plz refer to the paper for precise references). these dataset comes with ground truth mesh for each input image. Then  u run nextFace on these images and u compare the obj mesh of nextFace with the groud truth mesh. U will have to register the two meshes (using ICP or similar) and then compute the geometric/normal error on per vertex basis.. hope this help

**Comment by AndrewDQ** [comment]
Thanks for such a quick reply, I will give it a try.
