### ISSUE TITLE
The rendering results have noises

### ISSUE THREAD

**Issue by Seanseattle** [abdallahdib/NextFace#19]
Hello, thanks for your wonderful job! I have tried to render the image with ray tracing, but it seems to have lots of noise. Do you have any idea to denoise the images? Thank you again!

**Comment by abdallahdib** [comment]
Hi, yes u can play with the number of samples **rtSamples ** in **optimConfig.ini**. by default its set to 4000 which takes reasonable time on old gpus. If u have decent one u can try with higher values. A good value is to set rtSamples = 20000.
good luck

**Comment by Seanseattle** [comment]
Thanks for your reply.
