### ISSUE TITLE
how to transfer my face blend shape to a constructed model?

### ISSUE THREAD

**Issue by jinfagang** [abdallahdib/NextFace#26]
Say I have constructed a model of TomCruise, now I want using my face's expression to drive it, how to do that/.

**Comment by abdallahdib** [comment]
Hi, what u have to do is to reconstruct ur face using Nextface and then for each frame transfer ur expression coefficients to Tom Cruise. 
lets say u have a pipeline for tome cruise (check pipeline.py) and a pipeline for ur face. then u transfer the expression like this
tomPipeline.vExpCoeff = myPipeline.vExpCoeff

does this makes sense for u ?
