### ISSUE TITLE
about UV params

### ISSUE THREAD

**Issue by anewusername77** [abdallahdib/NextFace#35]
Dear author,
I'm new to CG，can you please teach me the way of calculating uvParams? and each params' meaning, like ```'uvFaces', 'uvMapFaces', 'uvValidUVMap', 'uvXYMap'and 'uvVertices'```.
thanks a lot!

**Comment by abdallahdib** [comment]
please refer to: 
https://github.com/abdallahdib/NextFace/issues/39#issuecomment-1242947705

**Comment by anewusername77** [comment]
thanks!
