### ISSUE TITLE
Stuck on Step #2 of 3

### ISSUE THREAD

**Issue by sensitivecereal** [abdallahdib/NextFace#40]
I installed everything correctly using the INSTALL file and when testing it, step 1 works fine, but then it gets stuck on step 2.
Says 0/401 and unknown iterations per second.
how long should I wait to see if it does eventually end?
I'm on a 3060ti. (And I tried with cpu, does the same thing)
thanks!

**Comment by TWIISTED-STUDIOS** [comment]
Just tried this and also stuck at the 2/3 mark, mine just says Optimizing Shape, Statistical etc etc ... And the. Just stops, I am having to use the CPU in the config as my GPU isn't supported.
