### ISSUE TITLE
detecting landmarks froze after using --sharedIdentity flag

### ISSUE THREAD

**Issue by xqyd** [abdallahdib/NextFace#5]
Hi, thanks for your great work!
One question. I was testing the code. I've noticed if you just finished a single image, and want to test another one, it froze when step into the "detecting landmarks...", and it will stay there for ever. Have to kill the console and restart it for the second image. I am using Win10. Any suggestions? Thanks!!!

**Comment by abdallahdib** [comment]
Hi,

that looks weird. What is the value of 'maxResolution' in ur optimConfig.ini ?

if u dont mind share the photos ur using so that i can debug on my side ? 

AD

**Comment by xqyd** [comment]
Sorry, my bad. after restart my console for the third time, I can't reproduce it. Consider it's something else caused this.
