### ISSUE TITLE
How to get the mesh as reported in your paper

### ISSUE THREAD

**Issue by xqyd** [abdallahdib/NextFace#7]
Hi, thanks for your great work!
I've run the following command line for s3.png and s4.png, and got some weired results. Can you tell me how to get the the same results as reported in your paper? Many thanks!

**python optimizer.py --input ./input/s3.png --output ./output**
loading optim config from:  ./optimConfig.ini
Loading Basel Face Model 2017 from ./baselMorphableModel/morphableModel-2017.pickle...
loading mesh normals...
loading uv parametrization...
loading landmarks association file...
creating sampler...
loading image from path:  ./input/s3.png
detecting landmarks...
init camera pose...
1/3 => Optimizing head pose and expressions using landmarks...
100%|█████████████████████████████████████████████████████████████████████████████| 2000/2000 [00:06<00:00, 301.50it/s]
2/3 => Optimizing shape, statistical albedos, expression, head pose and scene light...
100%|████████████████████████████████████████████████████████████████████████████████| 401/401 [02:28<00:00,  2.69it/s]
3/3 => finetuning albedos, shape, expression, head pose and scene light...
100%|████████████████████████████████████████████████████████████████████████████████| 101/101 [00:39<00:00,  2.59it/s]
took 3.25 minutes to optimize
saving to: ' ./output/s3.png/ '. hold on...
diffuseAlbedo.shape[0] =  1

And here are my results. As you can see, both subjects have Asian faces, the bridge of the nose is not so high, but the results are all European and American faces.
![image](https://user-images.githubusercontent.com/16912042/164650344-06daaea2-4095-47e2-8b7d-67544e1d7969.png)

**Comment by abdallahdib** [comment]
it is better to look to the mesh without textures (attached). please note that the statistical morphable model we use does not recover asian shapes properly as the dataset used to build this model are mainly european
![s3](https://user-images.githubusercontent.com/2556636/164676806-0ada2ded-5ad8-4fbf-8c4c-1eac735cf078.png)
![s4](https://user-images.githubusercontent.com/2556636/164676820-b80f7b45-9ef2-44fe-9813-f9275330fc01.png)

**Comment by xqyd** [comment]
Got it! Thanks!
