### ISSUE TITLE
Does it require similar lighting to for the multiple image method?

### ISSUE THREAD

**Issue by Michaelwhite34** [abdallahdib/NextFace#9]
Like same person under very different light environment.

**Comment by abdallahdib** [comment]
Hi, NextFace estimates a light per frame. that means if u have images for the same person under different lighting conditions, this should work with nextface.

**Comment by Michaelwhite34** [comment]
> Hi, NextFace estimates a light per frame. that means if u have images for the same person under different lighting conditions, this should work with nextface.

Another question is that if I use high res image and set textureResolution to a big number, will it have OOM issue or just slow speed ?

**Comment by abdallahdib** [comment]
if you want to use high res image, u may want to modify the maxResolution in optimConfig.ini. u can put it to higher number. if for instance u put it 1024, images with width or height large than 1024, it will scaled down to match 1024. but this will consume a lot of ur memory and makes the optimization very slow. if u have decent gpu with large memory u can try.

for textureResolution currently only 256x256 or 512x512 are supported
